apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: introspect-cluster
  region: us-east-1
  version: "1.33"
iam:
  withOIDC: true
managedNodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    minSize: 2
    maxSize: 4
    amiFamily: AmazonLinux2023
